---
- hosts: web
  become: yes
  gather_facts: false

  # vars: host="192.168.10.100"

  tasks:
  - name: update packages
    apt:
      update_cache: yes

  - name: upgrade packages
    apt:
      upgrade: yes

#  - name: Check if python is installed


  # - name: install python (v.3.8 upwards preferably)
  #   apt:
  #     name: python=3.9


  - name: install pip3
    apt:
      name: python3-pip


  - name: install Flask
    pip:
      name: flask

  - name: Clone into app repo
    git:
      repo: 'https://github.com/workwithstef/bookstore.git'
      clone: yes
      dest: /home/vagrant/bookstore/


  - name: Re-specify 'host' variable as required [py_db.py]
    shell: sed -i "s/localhost/192.168.10.200/" /home/vagrant/bookstore/py_db.py

  - name: Re-specify 'host' variable as required [flask_run.py]
    shell: sed -i "s/localhost/192.168.10.100/" /home/vagrant/bookstore/flask_run.py

  - name: Copy password file from app/ to bookstore/
    copy:
      src: /home/ubuntu/files/shhh.py
      dest: /home/vagrant/bookstore/


  - name: Install mysql-connector
    pip:
      name: mysql-connector

  - name: Install mysql-connector-python
    pip:
      name: mysql-connector-python

  # - name: Start app
